default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: transform_china
  pool: 5
  username: admin
  password: 12345678
  host: aa1khctdfbcclv3.c0hytilhpdt4.ap-northeast-1.rds.amazonaws.com

test:
  <<: *default
  database: transform_china

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: transform_china
  pool: 5
  username: admin
  password: 12345678
  host: aa1khctdfbcclv3.c0hytilhpdt4.ap-northeast-1.rds.amazonaws.com